import random
from collections import deque

import pygame

# ---------------------------------------------------------------------------
# Board / window configuration
# ---------------------------------------------------------------------------
BOARD_WIDTH = 10
BOARD_HEIGHT = 20

CELL_SIZE = 28
BOARD_ORIGIN_X = 200
BOARD_ORIGIN_Y = 60

WINDOW_SIZE = (700, 660)
FPS = 60

BLACK = (15, 15, 15)
WHITE = (245, 245, 245)
GRAY = (90, 90, 90)
PANEL_BG = (225, 225, 225)

# Side panels: hold box on the left, next-piece queue on the right.
NEXT_QUEUE_SIZE = 3
PREVIEW_CELL = 18
PANEL_WIDTH = 130
PANEL_SLOT_HEIGHT = 100

HOLD_BOX = (20, BOARD_ORIGIN_Y, PANEL_WIDTH, PANEL_SLOT_HEIGHT)
NEXT_BOX_X = BOARD_ORIGIN_X + BOARD_WIDTH * CELL_SIZE + 30
NEXT_BOXES = [
    (NEXT_BOX_X, BOARD_ORIGIN_Y + i * (PANEL_SLOT_HEIGHT + 10), PANEL_WIDTH, PANEL_SLOT_HEIGHT)
    for i in range(NEXT_QUEUE_SIZE)
]

PIECE_COLORS = {
    "I": (0, 240, 240),
    "O": (240, 240, 0),
    "T": (160, 0, 240),
    "S": (0, 240, 0),
    "Z": (240, 0, 0),
    "J": (0, 0, 240),
    "L": (240, 160, 0),
}

# ---------------------------------------------------------------------------
# Piece shapes
#
# Only the spawn orientation (state 0) is hand-written, as (row, col)
# offsets inside an NxN bounding box. States R (1), 2, and L (3) are
# generated by rotating that box 90 degrees clockwise three times, which
# is exactly how the SRS defines its four rotation states.
# ---------------------------------------------------------------------------
PIECE_SHAPES = {
    "I": (4, [(1, 0), (1, 1), (1, 2), (1, 3)]),
    "O": (2, [(0, 0), (0, 1), (1, 0), (1, 1)]),
    "T": (3, [(0, 1), (1, 0), (1, 1), (1, 2)]),
    "S": (3, [(0, 1), (0, 2), (1, 0), (1, 1)]),
    "Z": (3, [(0, 0), (0, 1), (1, 1), (1, 2)]),
    "J": (3, [(0, 0), (1, 0), (1, 1), (1, 2)]),
    "L": (3, [(0, 2), (1, 0), (1, 1), (1, 2)]),
}


def _rotate_cw(cells, box_size):
    """Rotate (row, col) cells 90 degrees clockwise inside a box_size
    square, with row increasing downward (screen convention)."""
    return [(c, box_size - 1 - r) for (r, c) in cells]


def _build_rotation_states():
    states = {}
    for name, (box_size, base_cells) in PIECE_SHAPES.items():
        rotations = [base_cells]
        for _ in range(3):
            rotations.append(_rotate_cw(rotations[-1], box_size))
        states[name] = {"box": box_size, "cells": rotations}
    return states


ROTATION_STATES = _build_rotation_states()

# ---------------------------------------------------------------------------
# SRS wall-kick tables: (from_state, to_state) -> ordered list of (dx, dy)
# offsets to try. dx = columns (right positive), dy = rows (down positive).
# The first offset that produces a legal position is used; O needs none,
# since its shape is identical in every rotation state.
# ---------------------------------------------------------------------------
JLSTZ_KICKS = {
    (0, 1): [(0, 0), (-1, 0), (-1, -1), (0, 2), (-1, 2)],
    (1, 0): [(0, 0), (1, 0), (1, 1), (0, -2), (1, -2)],
    (1, 2): [(0, 0), (1, 0), (1, 1), (0, -2), (1, -2)],
    (2, 1): [(0, 0), (-1, 0), (-1, -1), (0, 2), (-1, 2)],
    (2, 3): [(0, 0), (1, 0), (1, -1), (0, 2), (1, 2)],
    (3, 2): [(0, 0), (-1, 0), (-1, 1), (0, -2), (-1, -2)],
    (3, 0): [(0, 0), (-1, 0), (-1, 1), (0, -2), (-1, -2)],
    (0, 3): [(0, 0), (1, 0), (1, -1), (0, 2), (1, 2)],
}

I_KICKS = {
    (0, 1): [(0, 0), (-2, 0), (1, 0), (-2, 1), (1, -2)],
    (1, 0): [(0, 0), (2, 0), (-1, 0), (2, -1), (-1, 2)],
    (1, 2): [(0, 0), (-1, 0), (2, 0), (-1, -2), (2, 1)],
    (2, 1): [(0, 0), (1, 0), (-2, 0), (1, 2), (-2, -1)],
    (2, 3): [(0, 0), (2, 0), (-1, 0), (2, -1), (-1, 2)],
    (3, 2): [(0, 0), (-2, 0), (1, 0), (-2, 1), (1, -2)],
    (3, 0): [(0, 0), (1, 0), (-2, 0), (1, 2), (-2, -1)],
    (0, 3): [(0, 0), (-1, 0), (2, 0), (-1, -2), (2, 1)],
}

# ---------------------------------------------------------------------------
# Scoring & level-speed curve
# ---------------------------------------------------------------------------
LINE_CLEAR_SCORE = {1: 100, 2: 300, 3: 500, 4: 800}  # single/double/triple/tetris
LINES_PER_LEVEL = 10
SOFT_DROP_POINTS = 1
HARD_DROP_POINTS = 2

# ---------------------------------------------------------------------------
# Bonus features: combos, perfect clears, power-up pieces, wind
# ---------------------------------------------------------------------------
COMBO_POINTS = 50            # per extra consecutive clear, multiplied by level
PERFECT_CLEAR_SCORE = 2000   # multiplied by level, when the board ends up empty

POWERUP_EVERY_LINES = 5      # every N cleared lines, the next piece carries a power-up
POWERUP_TYPES = ("bomb", "laser", "freeze")
POWERUP_BLOCK_POINTS = 10    # per locked block destroyed by a bomb or laser
BOMB_RADIUS = 1              # 1 -> 3x3 blast area
FREEZE_SECONDS = 5.0
POWERUP_LETTERS = {"bomb": "B", "laser": "L", "freeze": "F"}
POWERUP_COLORS = {
    "bomb": (200, 30, 30),
    "laser": (230, 120, 0),
    "freeze": (0, 150, 220),
}

# Gravity is a (drow, dcol) pair. After a 4-line clear the next piece gets
# "wind": it is pushed sideways instead of down for that one piece.
NORMAL_GRAVITY = (1, 0)
WIND_DIRECTIONS = [(0, 1), (0, -1)]
WIND_COLOR = (120, 60, 200)
COMBO_COLOR = (0, 130, 60)


def gravity_interval(level):
    """Seconds between automatic downward steps, following the classic
    Tetris Guideline gravity curve (frames-per-row translated to seconds).
    Clamped so it never hits zero/negative at very high levels."""
    return max(0.05, (0.8 - (level - 1) * 0.007) ** (level - 1))


# ---------------------------------------------------------------------------
# Core data structures
# ---------------------------------------------------------------------------
class Piece:
    """A falling tetromino: its type, rotation state, board position, and
    an optional power-up ("bomb", "laser", "freeze" or None)."""

    def __init__(self, kind, power=None):
        self.kind = kind
        self.power = power
        self.rotation = 0
        box = ROTATION_STATES[kind]["box"]
        self.col = (BOARD_WIDTH - box) // 2
        self.row = 0

    def cells(self):
        """Absolute (row, col) board cells occupied at the current
        rotation and position."""
        offsets = ROTATION_STATES[self.kind]["cells"][self.rotation]
        return [(self.row + r, self.col + c) for (r, c) in offsets]


class Board:
    """The 10x20 well. Owns the locked-cell grid and line clearing."""

    def __init__(self, width=BOARD_WIDTH, height=BOARD_HEIGHT):
        self.width = width
        self.height = height
        self.grid = [[None] * width for _ in range(height)]

    def is_valid(self, cells):
        """True if every cell is in-bounds (horizontally and at the
        bottom) and unoccupied. Cells above the board (row < 0) are
        always allowed, so pieces can spawn partly off the top."""
        for row, col in cells:
            if col < 0 or col >= self.width or row >= self.height:
                return False
            if row >= 0 and self.grid[row][col] is not None:
                return False
        return True

    def lock(self, piece):
        for row, col in piece.cells():
            if row >= 0:
                self.grid[row][col] = piece.kind

    def clear_lines(self):
        """Remove every full row, shifting the rest down. Returns the
        number of lines cleared."""
        remaining = [row for row in self.grid if any(cell is None for cell in row)]
        cleared = self.height - len(remaining)
        if cleared:
            self.grid = [[None] * self.width for _ in range(cleared)] + remaining
        return cleared

    def is_empty(self):
        return all(cell is None for row in self.grid for cell in row)

    def top_row(self):
        """Index of the highest row containing a locked block, or
        self.height if the board is empty."""
        for r, row in enumerate(self.grid):
            if any(cell is not None for cell in row):
                return r
        return self.height

    def clear_cells(self, cells):
        """Empty the given (row, col) cells (out-of-bounds ones are
        ignored). Returns the list of cells that actually held a block."""
        removed = []
        for r, c in cells:
            if 0 <= r < self.height and 0 <= c < self.width and self.grid[r][c] is not None:
                self.grid[r][c] = None
                removed.append((r, c))
        return removed


class SevenBag:
    """Standard 7-bag randomizer: each piece type appears exactly once
    per bag, in shuffled order, before the bag refills. This avoids the
    long droughts/floods possible with tetris_ver2.py's uniform
    random.randint spawner."""

    def __init__(self):
        self._bag = []

    def next_piece(self):
        if not self._bag:
            self._bag = list(PIECE_SHAPES.keys())
            random.shuffle(self._bag)
        return self._bag.pop()


class Game:
    """Ties board + piece + randomizer + scoring/level together and
    exposes the actions the input layer drives."""

    def __init__(self):
        self.board = Board()
        self.bag = SevenBag()
        self.piece = None
        self.score = 0
        self.lines_cleared = 0
        self.level = 1
        self.state = "playing"
        self._fall_timer = 0.0

        # Bonus-feature state
        self.combo = 0                 # consecutive locks that cleared lines
        self.lines_since_powerup = 0   # progress toward the next power-up
        self.pending_power = None      # power-up the next queued piece will carry
        self.freeze_timer = 0.0        # seconds of gravity pause remaining
        self.gravity_dir = NORMAL_GRAVITY

        # Next-piece queue: always kept topped up to NEXT_QUEUE_SIZE so the
        # UI can show what's coming without consuming it.
        self.next_queue = deque()
        self._refill_queue()

        # Hold piece: starts empty; can_hold prevents hold/un-hold being
        # chained more than once per piece (the standard guideline rule).
        self.hold_kind = None
        self.hold_power = None
        self.can_hold = True

        self._spawn_piece()

    def _refill_queue(self):
        while len(self.next_queue) < NEXT_QUEUE_SIZE:
            self.next_queue.append(self.bag.next_piece())

    def _spawn_piece(self, kind=None, power=None, wind=False):
        if kind is None:
            # Fresh piece from the queue: it picks up any pending power-up.
            kind = self.next_queue.popleft()
            self._refill_queue()
            power = self.pending_power
            self.pending_power = None
        self.piece = Piece(kind, power)
        self.gravity_dir = NORMAL_GRAVITY
        if wind:
            self._apply_wind()
        if not self.board.is_valid(self.piece.cells()):
            self.state = "gameover"

    def _apply_wind(self):
        """Try to push the freshly spawned piece sideways. It starts on one
        wall, just above the stack, and slides toward the opposite wall.
        If there is no room (stack too tall), the piece falls normally."""
        drow, dcol = random.choice(WIND_DIRECTIONS)
        box = ROTATION_STATES[self.piece.kind]["box"]
        spawn_row = self.board.top_row() - box
        if spawn_row < 0:
            return
        spawn_col = 0 if dcol > 0 else self.board.width - box
        original = (self.piece.row, self.piece.col)
        self.piece.row, self.piece.col = spawn_row, spawn_col
        if self.board.is_valid(self.piece.cells()):
            self.gravity_dir = (drow, dcol)
        else:
            self.piece.row, self.piece.col = original

    def hold(self):
        """Swap the active piece into the hold slot. Only one hold is
        allowed per piece, reset when the active piece locks. Disabled
        while the piece is being blown sideways. A held piece keeps its
        power-up."""
        if self.state != "playing" or not self.can_hold:
            return
        if self.gravity_dir != NORMAL_GRAVITY:
            return
        current_kind, current_power = self.piece.kind, self.piece.power
        if self.hold_kind is None:
            self._spawn_piece()
        else:
            self._spawn_piece(kind=self.hold_kind, power=self.hold_power)
        self.hold_kind, self.hold_power = current_kind, current_power
        self.can_hold = False

    def move(self, dcol, drow):
        """Attempt to move the active piece; returns False and leaves it
        unchanged if that would collide."""
        self.piece.col += dcol
        self.piece.row += drow
        if not self.board.is_valid(self.piece.cells()):
            self.piece.col -= dcol
            self.piece.row -= drow
            return False
        return True

    def rotate(self, clockwise=True):
        if self.state != "playing" or self.piece.kind == "O":
            return
        old_state = self.piece.rotation
        new_state = (old_state + (1 if clockwise else -1)) % 4
        kicks = I_KICKS if self.piece.kind == "I" else JLSTZ_KICKS
        for dx, dy in kicks.get((old_state, new_state), [(0, 0)]):
            self.piece.rotation = new_state
            self.piece.col += dx
            self.piece.row += dy
            if self.board.is_valid(self.piece.cells()):
                return
            self.piece.col -= dx
            self.piece.row -= dy
        self.piece.rotation = old_state 

    def soft_drop(self):
        if self.state != "playing":
            return
        if self.gravity_dir != NORMAL_GRAVITY:
            # Wind: DOWN just steers the piece down; wind (or hard drop)
            # is what locks it.
            self.move(0, 1)
            return
        if self.move(0, 1):
            self.score += SOFT_DROP_POINTS
        else:
            self._lock_active_piece()

    def hard_drop(self):
        """Slide the piece along its gravity direction until it stops."""
        if self.state != "playing":
            return
        drow, dcol = self.gravity_dir
        dropped = 0
        while self.move(dcol, drow):
            dropped += 1
        self.score += dropped * HARD_DROP_POINTS
        self._lock_active_piece()

    def update(self, dt):
        """Advance gravity by dt seconds (paused while frozen)."""
        if self.state != "playing":
            return
        if self.freeze_timer > 0:
            self.freeze_timer = max(0.0, self.freeze_timer - dt)
            return
        self._fall_timer += dt
        if self._fall_timer >= gravity_interval(self.level):
            self._fall_timer = 0.0
            drow, dcol = self.gravity_dir
            if not self.move(dcol, drow):
                self._lock_active_piece()

    def _apply_powerup(self, piece):
        """Fire the locked piece's power-up, if it has one. The anchor is
        the piece's lowest cell, which is also where the 'B'/'L'/'F'
        marker is drawn."""
        if piece.power is None:
            return
        own = set(piece.cells())
        anchor_row, anchor_col = max(piece.cells(), key=lambda rc: rc[0])
        targets = []
        if piece.power == "bomb":
            targets = [
                (r, c)
                for r in range(anchor_row - BOMB_RADIUS, anchor_row + BOMB_RADIUS + 1)
                for c in range(anchor_col - BOMB_RADIUS, anchor_col + BOMB_RADIUS + 1)
            ]
        elif piece.power == "laser":
            targets = [(r, anchor_col) for r in range(self.board.height)]
        elif piece.power == "freeze":
            self.freeze_timer = FREEZE_SECONDS
        removed = self.board.clear_cells(targets)
        # Only reward blocks that were already on the board, not the piece itself.
        self.score += sum(1 for cell in removed if cell not in own) * POWERUP_BLOCK_POINTS

    def _lock_active_piece(self):
        piece = self.piece
        self.board.lock(piece)
        self._apply_powerup(piece)

        cleared = self.board.clear_lines()
        if cleared:
            self.combo += 1
            self.lines_cleared += cleared
            self.lines_since_powerup += cleared
            self.score += LINE_CLEAR_SCORE[cleared] * self.level
            if self.combo > 1:
                self.score += COMBO_POINTS * (self.combo - 1) * self.level
            self.level = 1 + self.lines_cleared // LINES_PER_LEVEL
            if self.lines_since_powerup >= POWERUP_EVERY_LINES:
                self.lines_since_powerup -= POWERUP_EVERY_LINES
                self.pending_power = random.choice(POWERUP_TYPES)
        else:
            self.combo = 0

        if self.board.is_empty():
            self.score += PERFECT_CLEAR_SCORE * self.level

        self.can_hold = True
        self._fall_timer = 0.0
        self._spawn_piece(wind=(cleared == 4))


# ---------------------------------------------------------------------------
# Rendering (thin - the classes above have no pygame dependency in their
# logic, only this section touches the screen)
# ---------------------------------------------------------------------------
def draw_board(screen, board):
    for row in range(board.height):
        for col in range(board.width):
            x = BOARD_ORIGIN_X + col * CELL_SIZE
            y = BOARD_ORIGIN_Y + row * CELL_SIZE
            pygame.draw.rect(screen, GRAY, (x, y, CELL_SIZE, CELL_SIZE), 1)
            kind = board.grid[row][col]
            if kind:
                pygame.draw.rect(
                    screen, PIECE_COLORS[kind],
                    (x + 1, y + 1, CELL_SIZE - 2, CELL_SIZE - 2),
                )


def draw_piece(screen, piece, small_font):
    color = PIECE_COLORS[piece.kind]
    cells = piece.cells()
    # Power-up pieces get a black border, and a lettered marker on the
    # anchor (lowest) cell, which is where the effect will fire.
    anchor = max(cells, key=lambda rc: rc[0]) if piece.power else None
    for row, col in cells:
        if row < 0:
            continue
        x = BOARD_ORIGIN_X + col * CELL_SIZE
        y = BOARD_ORIGIN_Y + row * CELL_SIZE
        pygame.draw.rect(screen, color, (x + 1, y + 1, CELL_SIZE - 2, CELL_SIZE - 2))
        if piece.power:
            pygame.draw.rect(screen, BLACK, (x + 1, y + 1, CELL_SIZE - 2, CELL_SIZE - 2), 3)
            if (row, col) == anchor:
                pygame.draw.rect(screen, WHITE, (x + 4, y + 4, CELL_SIZE - 8, CELL_SIZE - 8))
                letter = small_font.render(
                    POWERUP_LETTERS[piece.power], True, POWERUP_COLORS[piece.power]
                )
                screen.blit(letter, letter.get_rect(center=(x + CELL_SIZE // 2, y + CELL_SIZE // 2)))


def ghost_cells(board, piece, gravity=NORMAL_GRAVITY):
    # Show where the piece will end up if it keeps moving along gravity
    drow, dcol = gravity
    start_row, start_col = piece.row, piece.col
    while board.is_valid(piece.cells()):
        piece.row += drow
        piece.col += dcol
    piece.row -= drow
    piece.col -= dcol
    landed = piece.cells()
    piece.row, piece.col = start_row, start_col
    return landed


def draw_ghost(screen, board, piece, gravity=NORMAL_GRAVITY):
    color = PIECE_COLORS[piece.kind]
    for row, col in ghost_cells(board, piece, gravity):
        if row < 0:
            continue
        x = BOARD_ORIGIN_X + col * CELL_SIZE
        y = BOARD_ORIGIN_Y + row * CELL_SIZE
        pygame.draw.rect(screen, color, (x + 3, y + 3, CELL_SIZE - 6, CELL_SIZE - 6), 2)


def draw_mini_piece(screen, kind, box_x, box_y, box_w, box_h):
    """Draw a small, centered preview of a piece's spawn orientation,
    used for both the hold slot and the next-piece queue."""
    box_size = ROTATION_STATES[kind]["box"]
    cells = ROTATION_STATES[kind]["cells"][0]
    piece_px = box_size * PREVIEW_CELL
    offset_x = box_x + (box_w - piece_px) // 2
    offset_y = box_y + (box_h - piece_px) // 2
    color = PIECE_COLORS[kind]
    for r, c in cells:
        x = offset_x + c * PREVIEW_CELL
        y = offset_y + r * PREVIEW_CELL
        pygame.draw.rect(screen, color, (x + 1, y + 1, PREVIEW_CELL - 2, PREVIEW_CELL - 2))


def draw_panel_slot(screen, rect, label, font, kind=None):
    x, y, w, h = rect
    pygame.draw.rect(screen, PANEL_BG, rect)
    pygame.draw.rect(screen, GRAY, rect, 2)
    screen.blit(font.render(label, True, BLACK), (x + 6, y - 22))
    if kind is not None:
        draw_mini_piece(screen, kind, x, y, w, h)


def draw_hold(screen, font, game):
    draw_panel_slot(screen, HOLD_BOX, "HOLD", font, game.hold_kind)
    if game.hold_power:
        label = font.render(game.hold_power.upper(), True, POWERUP_COLORS[game.hold_power])
        screen.blit(label, (HOLD_BOX[0] + 6, HOLD_BOX[1] + HOLD_BOX[3] + 4))


def draw_status(screen, font, game):
    """Combo, queued power-up, freeze timer and wind indicators, drawn
    below the score/level/lines block."""
    lines = []
    if game.combo >= 2:
        lines.append((f"Combo x{game.combo}", COMBO_COLOR))
    if game.pending_power:
        lines.append((f"Next: {game.pending_power.upper()}", POWERUP_COLORS[game.pending_power]))
    if game.freeze_timer > 0:
        lines.append((f"FROZEN {game.freeze_timer:.1f}s", POWERUP_COLORS["freeze"]))
    if game.gravity_dir != NORMAL_GRAVITY:
        arrows = ">>>" if game.gravity_dir[1] > 0 else "<<<"
        lines.append((f"WIND {arrows}", WIND_COLOR))
    start_y = HOLD_BOX[1] + HOLD_BOX[3] + 30 + 3 * 26 + 10
    for i, (text, color) in enumerate(lines):
        screen.blit(font.render(text, True, color), (HOLD_BOX[0], start_y + i * 26))


def draw_next_queue(screen, font, game):
    for i, box in enumerate(NEXT_BOXES):
        label = "NEXT" if i == 0 else ""
        draw_panel_slot(screen, box, label, font, game.next_queue[i])


def draw_hud(screen, font, game):
    lines = [f"Score: {game.score}", f"Level: {game.level}", f"Lines: {game.lines_cleared}"]
    for i, line in enumerate(lines):
        screen.blit(font.render(line, True, BLACK), (HOLD_BOX[0], HOLD_BOX[1] + HOLD_BOX[3] + 30 + i * 26))


def draw_game_over(screen, big_font, small_font):
    board_center_x = BOARD_ORIGIN_X + (BOARD_WIDTH * CELL_SIZE) // 2
    board_center_y = BOARD_ORIGIN_Y + (BOARD_HEIGHT * CELL_SIZE) // 2

    title = big_font.render("GAME OVER", True, (220, 60, 40))
    subtitle = small_font.render("R to restart  -  Q to quit", True, BLACK)
    screen.blit(title, title.get_rect(center=(board_center_x, board_center_y - 20)))
    screen.blit(subtitle, subtitle.get_rect(center=(board_center_x, board_center_y + 30)))


def main():
    pygame.init()
    screen = pygame.display.set_mode(WINDOW_SIZE)
    pygame.display.set_caption("Tetris")
    clock = pygame.time.Clock()
    font = pygame.font.SysFont("Calibri", 22, True)
    big_font = pygame.font.SysFont("Calibri", 46, True)
    small_font = pygame.font.SysFont("Calibri", 18, True)

    game = Game()
    soft_dropping = False
    running = True

    while running:
        dt = clock.tick(FPS) / 1000.0

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            elif event.type == pygame.KEYDOWN:
                if event.key == pygame.K_LEFT:
                    game.move(-1, 0)
                elif event.key == pygame.K_RIGHT:
                    game.move(1, 0)
                elif event.key == pygame.K_UP:
                    game.rotate(clockwise=True)
                elif event.key == pygame.K_z:
                    game.rotate(clockwise=False)
                elif event.key == pygame.K_SPACE:
                    game.hard_drop()
                elif event.key == pygame.K_c:
                    game.hold()
                elif event.key == pygame.K_DOWN:
                    soft_dropping = True
                elif event.key == pygame.K_r and game.state == "gameover":
                    game = Game()
                elif event.key == pygame.K_q and game.state == "gameover":
                    running = False
            elif event.type == pygame.KEYUP and event.key == pygame.K_DOWN:
                soft_dropping = False

        if game.state == "playing":
            if soft_dropping:
                game.soft_drop()
            game.update(dt)

        screen.fill(WHITE)
        draw_board(screen, game.board)
        if game.state == "playing":
            draw_ghost(screen, game.board, game.piece, game.gravity_dir)
            draw_piece(screen, game.piece, small_font)
        draw_hold(screen, font, game)
        draw_next_queue(screen, font, game)
        draw_hud(screen, font, game)
        draw_status(screen, font, game)
        if game.state == "gameover":
            draw_game_over(screen, big_font, font)

        pygame.display.flip()

    pygame.quit()


if __name__ == "__main__":
    main()
